In [8]:
import numpy as np

In [9]:
lista = [1, 2, 3]

In [10]:
lista

[1, 2, 3]

In [11]:
np.array(lista)

array([1, 2, 3])

In [12]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [38]:
arr = np.zeros((5,5))

In [39]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [47]:
np.random.rand(5)

array([0.76297448, 0.65589353, 0.0478138 , 0.45703737, 0.61242599])

In [48]:
np.random.randn(5)

array([ 1.36249856,  1.34474938, -1.17592961, -0.24858265, -0.49117211])

In [54]:
np.random.randint(0,101,10)

array([ 5, 26,  0, 49, 21, 18, 71, 27, 59, 47])

In [55]:
np.random.rand(5) * 100

array([28.31393176, 97.80125185, 75.05156536, 43.52854908, 27.79664802])

In [57]:
np.round(np.random.rand(5) * 100, 0)

array([86., 61., 79., 47.,  8.])

In [59]:
arr = np.random.rand(25)

In [60]:
arr

array([0.45157876, 0.36197346, 0.77056586, 0.47859199, 0.64953898,
       0.29500777, 0.24202342, 0.64705577, 0.19546259, 0.61009653,
       0.62271239, 0.38817943, 0.8826075 , 0.05538908, 0.37863308,
       0.60773316, 0.79716297, 0.88606381, 0.75681249, 0.48140078,
       0.90638862, 0.4143244 , 0.12550659, 0.54629298, 0.48188513])

In [61]:
arr.reshape((5,5))

array([[0.45157876, 0.36197346, 0.77056586, 0.47859199, 0.64953898],
       [0.29500777, 0.24202342, 0.64705577, 0.19546259, 0.61009653],
       [0.62271239, 0.38817943, 0.8826075 , 0.05538908, 0.37863308],
       [0.60773316, 0.79716297, 0.88606381, 0.75681249, 0.48140078],
       [0.90638862, 0.4143244 , 0.12550659, 0.54629298, 0.48188513]])

In [62]:
arr = arr.reshape((5,5))

In [63]:
arr

array([[0.45157876, 0.36197346, 0.77056586, 0.47859199, 0.64953898],
       [0.29500777, 0.24202342, 0.64705577, 0.19546259, 0.61009653],
       [0.62271239, 0.38817943, 0.8826075 , 0.05538908, 0.37863308],
       [0.60773316, 0.79716297, 0.88606381, 0.75681249, 0.48140078],
       [0.90638862, 0.4143244 , 0.12550659, 0.54629298, 0.48188513]])

In [64]:
arr.shape

(5, 5)

In [65]:
arr.max()

0.9063886164393833

In [68]:
arr.min()

0.05538908096219619

In [70]:
arr.argmax()

20